refactor: Rewrite input check

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -43,21 +43,19 @@ runs:
           OPTIONS="${{ inputs.options }}"
         fi
 
-        # 检查文件是否存在
-        if [ ! -f "${{ inputs.data }}" ]; then
-          # 检查是否为合法 json 字符串
-          echo "${{ inputs.data }}" | jq . > /dev/null 2>&1
-          if [ $? -ne 0 ]; then
-            echo "::error::File '${{ inputs.data }}' does not exist."
-            echo "::error::String '${{ inputs.data }}' is not a valid json."
-            exit 1
-          fi
-          # 是合法 json 字符串
-          RESULT=$(echo "${{ inputs.data }}" | jq $RAW_FLAG $OPTIONS '${{ inputs.filter }}')
-        else
-          # 文件存在
-          RESULT=$(jq $RAW_FLAG $OPTIONS '${{ inputs.filter }}' "${{ inputs.data }}")
-        fi
+        INPUT_DATA='${{ inputs.data }}'
 
+        # 检查是否为合法 JSON 字符串
+        if echo "$INPUT_DATA" | jq . > /dev/null 2>&1; then
+          # 是合法的 JSON 字符串
+          RESULT=$(echo "$INPUT_DATA" | jq $RAW_FLAG $OPTIONS '${{ inputs.filter }}')
+        # 检查是否为存在的文件
+        elif [ -f "$INPUT_DATA" ]; then
+          # 是存在的文件
+          RESULT=$(jq $RAW_FLAG $OPTIONS '${{ inputs.filter }}' '$INPUT_DATA')
+        else
+          echo "::error::Input '$INPUT_DATA' is neither a valid JSON string nor an existing file."
+          exit 1
+        fi
 
         echo "result=$RESULT" >> $GITHUB_OUTPUT
